import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const HomeStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: '#f0f2f5' },
  headerSafeArea: { backgroundColor: '#004a99' },
  header: { backgroundColor: '#004a99', padding: 15 ,borderBottomWidth:2,borderBottomColor:'#f38120'},
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  logoContainer: { flexDirection: 'row', alignItems: 'center' },
  logoPlaceholder: { width: 45, height: 45, borderRadius: 23, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center' },
  logoImage: { width: "100%", height: "100%",borderRadius: 23,resizeMode: 'cover', justifyContent: 'center', alignItems: 'center', backgroundColor: '#e8e8e8' },
  headerTextContainer: { marginLeft: 10 },
  schoolName: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  subHeader: { color: 'white', fontSize: 10, marginTop: 2 },
  scrollContainer: { flex: 1 },
  heroContainer: { height: 200, width: '100%' },
  heroPlaceholder: { flex: 1, backgroundColor: '#555', justifyContent: 'center', alignItems: 'center' },
  heroImage: { width: '100%', height: '100%', resizeMode: 'cover', justifyContent: 'center', alignItems: 'center', backgroundColor: '#e8e8e8' },
  slideshowContainer: { flex: 1, position: 'relative' },
  dotsContainer: { position: 'absolute', bottom: 10, left: 0, right: 0, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  dot: { width: 8, height: 8, borderRadius: 4, marginHorizontal: 4 },
  activeDot: { backgroundColor: '#fff', opacity: 1 },
  inactiveDot: { backgroundColor: '#fff', opacity: 0.5 },
  loadingText: { fontSize: 16, color: '#999', fontWeight: '600' },
  errorText: { fontSize: 16, color: '#d32f2f', fontWeight: '600' },
  card: { margin: 12, backgroundColor: 'white', borderRadius: 8, elevation: 3, overflow: 'hidden' },
  noticeHeader: { backgroundColor: '#f38120', padding: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  noticeTitle: { color: 'white', fontWeight: 'bold', marginLeft: 8, fontSize: 16 },
  viewAllBtnHeader: { backgroundColor: 'white', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, flexDirection: 'row', alignItems: 'center' },
  viewAllTextHeader: { color: '#0056b3', fontWeight: 'bold', fontSize: 12 },
  noticeList: { padding: 15 },
  noticeItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  bullet: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#f38120', marginRight: 10 },
  noticeText: { fontSize: 13, color: '#444' },
  viewAllInline: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center' },
  viewAllInlineText: { color: '#0056b3', fontWeight: 'bold', fontSize: 14 },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 12 },
  gridBox: { width: '23%', backgroundColor: 'white', borderRadius: 8, padding: 10, alignItems: 'center', elevation: 2, marginBottom: 10 },
  iconWrapper: { marginBottom: 5 },
  gridLabel: { fontSize: 10, textAlign: 'center', color: '#333', fontWeight: '600' },
  sectionCard: { margin: 12, backgroundColor: 'white', padding: 15, borderRadius: 8, elevation: 2 },
  sectionTitleMain: { fontSize: 18, fontWeight: 'bold', color: '#004a99' },
  titleUnderline: { height: 1, backgroundColor: '#eee', marginVertical: 10 },
  sectionPara: { fontSize: 14, color: '#555', lineHeight: 22 },
  readMore: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  readMoreText: { color: '#0056b3', fontWeight: 'bold' },
  coursesList: { marginTop: 12 },
  courseItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, paddingVertical: 4 },
  courseBullet: { fontSize: 20, color: '#f38120', marginRight: 10, fontWeight: 'bold', lineHeight: 20 },
  courseText: { fontSize: 14, color: '#333', fontWeight: '500', lineHeight: 20, flex: 1 },
  facultyHeader: { paddingHorizontal: 15, marginTop: 10 },
  facultyScroll: { paddingLeft: 12, marginTop: 10 },
  fCard: { width: 150, marginRight: 15, borderRadius: 8, overflow: 'hidden', backgroundColor: 'white', elevation: 3, marginBottom: 10 },
  fImagePlaceholder: { height: 130, backgroundColor: '#ddd' },
  fInfo: { backgroundColor: '#004a99', padding: 10 },
  fName: { color: 'white', fontSize: 13, fontWeight: 'bold' },
  fRole: { color: '#ddd', fontSize: 11 },
  contentArea: { flex: 1 },
});

export default HomeStyles;